listssrht/blueprints/archives.py
from datetime import datetime, timedelta
from flask import Blueprint, render_template, abort, request, redirect, url_for
from flask import Response, session, send_file
from sqlalchemy import String, select, cast, or_
from sqlalchemy.sql.functions import coalesce
from srht.config import cfg
from srht.database import db
from srht.search import search_by
from srht.flask import paginate_query
from srht.oauth import current_user, loginrequired, UserType
from srht.validation import Validation
from listssrht.filters import post_address
from listssrht.types import List, User, Email, Subscription, ListAccess, Access, Visibility
from listssrht.types import Patchset, PatchsetStatus
from listssrht.process import forward_thread
from listssrht.webhooks import ListWebhook, UserWebhook
from urllib.parse import quote, urlencode
import email
import email.policy
import email.utils
import hashlib
import mailbox
import os

archives = Blueprint("archives", __name__)

msgauth_server = cfg("lists.sr.ht", "msgauth-server", default=None)

def get_list(owner_name, list_name, current_user=current_user):
    if owner_name and owner_name.startswith('~'):
        owner_name = owner_name[1:]
        owner = User.query.filter(User.username == owner_name).one_or_none()
        if not owner:
            return None, None, None
    else:
        # TODO: orgs
        return None, None, None
    ml = (List.query
            .filter(List.name == list_name)
            .filter(List.owner_id == owner.id)
            .one_or_none()
        )
    if not ml:
        return None, None, None
    access = get_access(ml, user=current_user)
    if access == ListAccess.none and ml.visibility == Visibility.PRIVATE:
        abort(401)
    return owner, ml, access

def get_access(ml, user=None):
    user = user or current_user

    # Anonymous
    if not user:
        if ml.visibility == Visibility.PRIVATE:
            return ListAccess.none
        return ml.default_access

    # Owner
    if user.id == ml.owner_id:
        return ListAccess.all

    # Admin
    if user.user_type == UserType.admin:
        return ListAccess.all

    # ACL entry?
    user_access = Access.query.filter_by(list=ml, user=user).first()
    if user_access:
        return user_access.permissions

    if ml.visibility == Visibility.PRIVATE:
        return ListAccess.none
    return ml.default_access

def apply_search(query, search):
    if not search:
        return query.filter(Email.parent_id == None)

    def canonicalize(header):
        return "-".join(h[0].upper() + h[1:] for h in header.split("-"))

    def header_filter(name, value):
        header = cast(Email.headers[name], String)
        return header.ilike(f"%{value}%")

    def user_alias(header, value):
        if current_user and value == "me":
            value = current_user.email
        elif "@" not in value:
            # SELECT email.subject, ... FROM "email"  -- from toplevel query
            # WHERE ...
            # AND CAST(email.headers -> 'From' AS VARCHAR)
            #     ILIKE COALESCE((SELECT '%%' || "user".email || '%%' FROM "user"
            #                             WHERE "user".username = 'zupa'),
            #                            '%%zupa%%')
            # AND CAST(email.headers -> 'Cc'   AS VARCHAR)
            #     ILIKE COALESCE((SELECT '%%' || "user".email || '%%' FROM "user"
            #                             WHERE "user".username = 'zeta'),
            #                            '%%zeta%%')
            # ORDER BY email.updated DESC;
            #
            # Try to find a user with the specified name,
            # or default to fuzzy search if no such user exists

            username = value
            if username.startswith("~"):
                username = username[1:]

            header = cast(Email.headers[header], String)
            return header.ilike(coalesce(select('%' + User.email + '%')
                    .where(User.username == username).as_scalar(),
                    f"%{username}%"))

        return header_filter(header, value)

    def patchset_status(value):
        status = getattr(PatchsetStatus, value, None)
        if not status:
            raise ValueError(f"Invalid patchset status: '{value}'")

        return Email.patchset.has(Patchset.status == status)

    return search_by(query, search, [Email.body, Email.subject], {
        "is": lambda v: {
            "patch": Email.is_patch,
            "reply": Email.parent_id != None,
            "request-pull": Email.is_request_pull,
            "thread": Email.nreplies > 0,
        }.get(v, False),
        "from": lambda v: user_alias("From", v),
        "to": lambda v: user_alias("To", v),
        "cc": lambda v: user_alias("Cc", v),
        "status": patchset_status,
        "prefix": lambda v: Email.patchset.has(Patchset.prefix == v),
        "sender-timestamp": lambda v: (
            Email.message_date == datetime.utcfromtimestamp(int(v))),
    }, fallback_fn=header_filter)

def _dkim_explain(status, domain):
    return {
        "pass": f"Valid DKIM signature for {domain}",
        "fail": f"Invalid DKIM signature for {domain}. The message may have" +
            f" been tampered with, or the mail server at {domain} is" +
            " misconfigured.",
        "policy": "This email has a DKIM signature, but is for some reason" +
            " unsuitable for the policy of the recipient.",
        "neutral": "This email has a DKIM signature, but it has syntax errors" +
            " or other problems rendering it meaningless. This is generally" +
            f" a configuration error with the mail server at {domain}.",
        "temperror": "A temporary error occured while validating this DKIM" +
            " signature.",
        "permerror": "A permanent error occured while validating this DKIM" +
            " signature, such as a missing or invalid header. This is" +
            f" generally a configuration error with the mail server at {domain}."
    }.get(status)

def parse_auth_result(mail, method):
    address = email.utils.parseaddr(mail["From"])[1]
    mailboxhost = address.split("@", 2)
    if len(mailboxhost) < 2:
        return None, None
    domain = mailboxhost[1].lower()
    if msgauth_server is None:
        return None, None
    fields = mail.get_all("Authentication-Results", failobj=[])
    for field in fields:
        parts = field.lower().replace(';', ' ').split()
        host = parts.pop(0)
        if host != msgauth_server:
            continue
        if parts[0].isalnum():
            version = parts.pop(0)
            if version != "1":
                continue
        [meth, result] = parts.pop(0).split('=', 2)
        if meth != method.lower():
            continue
        if not "header.d=" + domain in parts:
            continue
        return result, _dkim_explain(result, domain)
    return None, _dkim_explain("none", domain)

@archives.route("/<owner_name>/<list_name>")
def archive(owner_name, list_name):
    owner, ml, access = get_list(owner_name, list_name)
    if not ml:
        abort(404)
    threads = (Email.query
            .filter(Email.list_id == ml.id)
        ).order_by(Email.updated.desc())

    search = request.args.get("search")
    search_error = None
    try:
        threads = apply_search(threads, search)
    except ValueError as ex:
        search_error = str(ex)

    threads, pagination = paginate_query(threads)

    subscription = None
    if current_user:
        subscription = (Subscription.query
                .filter(Subscription.list_id == ml.id)
                .filter(Subscription.user_id == current_user.id)).one_or_none()

    message = session.pop("message", None)
    return render_template("archive.html",
            view="archives", owner=owner, ml=ml, threads=threads,
            access=access, ListAccess=ListAccess,
            search=search, search_error=search_error, subscription=subscription,
            parseaddr=email.utils.parseaddr,
            message=message, **pagination)

@archives.route("/<owner_name>/<list_name>/<path:message_id>")
def thread(owner_name, list_name, message_id):
    owner, ml, access = get_list(owner_name, list_name)
    if not ml:
        abort(404)
    if ListAccess.browse not in access:
        abort(403)
    thread = (Email.query
            .filter(Email.message_id == message_id)
            .filter(Email.list_id == ml.id)
        ).one_or_none()
    if not thread:
        abort(404)
    if thread.thread_id != None:
        return redirect(url_for("archives.thread",
            owner_name=owner_name,
            list_name=list_name,
            message_id=thread.thread.message_id) + "#" + thread.message_id)

    messages = (Email.query
            .filter(Email.thread_id == thread.id)
            .order_by(Email.created)).all()

    def reply_to(msg):
        params = {
            "cc": msg.parsed()['From'],
            "in-reply-to": msg.message_id,
            "subject": (f"Re: {msg.subject}"
                if not msg.subject.lower().startswith("re:")
                else msg.subject),
        }
        pa = post_address(msg.list)
        if pa.startswith("mailto:"):
            return f"{pa}?{urlencode(params, quote_via=quote)}"
        else:
            return f"mailto:{pa}?{urlencode(params, quote_via=quote)}"

    user_message = session.pop("message", None)
    return render_template("thread.html", view="archives", owner=owner,
            access=access, ListAccess=ListAccess,
            ml=ml, thread=thread, messages=messages,
            parseaddr=email.utils.parseaddr,
            parse_auth_result=parse_auth_result,
            reply_to=reply_to,
            user_message=user_message)

@archives.route("/<owner_name>/<list_name>/<path:message_id>/raw")
def raw(owner_name, list_name, message_id):
    owner, ml, access = get_list(owner_name, list_name)
    if not ml:
        abort(404)
    if ListAccess.browse not in access:
        abort(403)
    message = (Email.query

listssrht/blueprints/user.py
from email.mime.text import MIMEText
from email.utils import parseaddr, formatdate, make_msgid
from flask import current_app, Blueprint, render_template, request, redirect, url_for, abort
from flask import session
from srht.config import cfg, cfgi
from srht.database import db
from srht.oauth import UserType, current_user, loginrequired
from srht.flask import paginate_query
from srht.graphql import exec_gql
from srht.search import search_by
from srht.validation import Validation
from sqlalchemy import or_
from listssrht.types import List, ListAccess, User, Email, Subscription, Mirror, Visibility
from listssrht.webhooks import UserWebhook
import re
import smtplib

user = Blueprint("user", __name__)

smtp_host = cfg("mail", "smtp-host", default=None)
smtp_port = cfgi("mail", "smtp-port", default=None)
smtp_user = cfg("mail", "smtp-user", default=None)
smtp_password = cfg("mail", "smtp-password", default=None)

@user.route("/")
def index():
    if not current_user:
        return render_template("index.html")
    recent = (Email.query
            .join(List)
            .join(Subscription)
            .filter(Email.list_id == List.id)
            .filter(Subscription.list_id == List.id)
            .filter(Subscription.user_id == current_user.id)
            .order_by(Email.created.desc())).limit(10).all()
    subs = [sub.list for sub in (Subscription.query
            .join(List)
            .filter(Subscription.user_id == current_user.id)
            .order_by(List.updated.desc())).limit(10).all()]
    notice = session.pop("notice", None)
    return render_template("dashboard.html", recent=recent,
            subs=subs, notice=notice)

@user.route("/~<username>")
def user_profile(username):
    user = User.query.filter(User.username == username).first()
    if not user:
        abort(404)
    recent = Email.query.filter(Email.sender_id == user.id)
    lists = List.query.filter(List.owner_id == user.id)

    if not current_user or current_user.id != user.id:
        lists = lists.filter(List.visibility == Visibility.PUBLIC)
        recent = (recent.join(List)
                 .filter(List.visibility == Visibility.PUBLIC)
                 .filter(List.default_access == ListAccess.normal.value))

    recent = recent.order_by(Email.created.desc()).limit(10).all()
    lists = lists.order_by(List.updated.desc()).limit(10).all()

    return render_template("user.html",
            user=user, recent=recent, lists=lists, parseaddr=parseaddr)

@user.route("/lists/~<username>")
def lists_for_user(username):
    user = User.query.filter(User.username == username).first()
    if not user:
        abort(404)
    lists = List.query.filter(List.owner_id == user.id)

    if not current_user or current_user.id != user.id:
        lists = lists.filter(List.visibility == Visibility.PUBLIC)

    lists = lists.order_by(List.updated.desc())
    terms = request.args.get('search')
    if terms:
        lists = search_by(lists, terms, [List.name, List.description], {})
    lists, pagination = paginate_query(lists)

    return render_template("user-lists.html",
            user=user, lists=lists, search=terms, **pagination)

@user.route("/lists/create")
@loginrequired
def create_list_GET():
    if (cfg("lists.sr.ht", "allow-new-lists", default="yes") != "yes"
            and current_user.user_type != UserType.admin):
        abort(401)
    return render_template("create.html")

@user.route("/lists/create", methods=["POST"])
def create_list_POST():
    if (cfg("lists.sr.ht", "allow-new-lists", default="yes") != "yes"
            and current_user.user_type != UserType.admin):
        abort(401)

    valid = Validation(request)
    name = valid.require("name", friendly_name="Name")
    description = valid.optional("description")
    visibility = valid.require("visibility")
    if not valid.ok:
        return render_template("create.html", **valid.kwargs)

    resp = exec_gql(current_app.site, """
        mutation CreateMailingList($name: String!, $description: String, $visibility: Visibility!) {
            createMailingList(name: $name, description: $description, visibility: $visibility) {
                name
                owner {
                    canonicalName
                }
            }
        }
    """, valid=valid, name=name, description=description, visibility=visibility)

    if not valid.ok:
        return render_template("create.html", **valid.kwargs)

    resp = resp["createMailingList"]
    return redirect(url_for("archives.archive",
            owner_name=resp["owner"]["canonicalName"],
            list_name=resp["name"]))

@user.route("/lists/create-mirror")
@loginrequired
def create_mirror_GET():
    return render_template("create-mirror.html")

def mirror_subscribe(ml, mirror):
    posting_domain = cfg("lists.sr.ht", "posting-domain")
    list_name = "u.{}.{}".format(ml.owner.username, ml.name)

    smtp = smtplib.SMTP(smtp_host, smtp_port)
    smtp.ehlo()
    smtp.starttls()
    smtp.login(smtp_user, smtp_password)

    mail = MIMEText(f"Subscription request for {posting_domain} on behalf of "
        f"{ml.owner.canonical_name}\n\n"
        "If this email is unexpected, feel free to ignore it, or send "
        "questions to:\n\n"
        f"{cfg('sr.ht', 'owner-name')} <{cfg('sr.ht', 'owner-email')}>")
    mail["X-Mirroring-To"] = posting_domain
    mail["Subject"] = "subscribe"
    mail["To"] = mirror.list_subscribe
    mail["From"] = f"{posting_domain} mirror <{list_name}@{posting_domain}>"
    mail["Date"] = formatdate()
    mail["Message-ID"] = make_msgid()
    smtp.sendmail(smtp_user, [mirror.list_subscribe], mail.as_string(
        unixfrom=True, maxheaderlen=998))
    smtp.quit()

@user.route("/lists/create-mirror", methods=["POST"])
@loginrequired
def create_mirror_POST():
    valid = Validation(request)
    ml = List(current_user, valid)
    address = valid.require("address", friendly_name="Subscription address")
    valid.expect(not address or "@" in address,
            "A valid email address is required", field="address")
    weird_ok = valid.optional("weird-email-okay")
    valid.expect(not address or weird_ok == "yes" or "subscribe" in address,
            "This address does not look like a subscription address. Double "
            "check it and click 'Create' if you're certain.", field="address")
    if not valid.ok:
        return render_template("create-mirror.html", **valid.kwargs)

    posting_domain = cfg("lists.sr.ht", "posting-domain")

    user, domain = address.split("@")
    valid.expect(domain != posting_domain,
            "You can't mirror a list from {{cfg('sr.ht', 'site-name')}}!",
            field="address")
    if not valid.ok:
        return render_template("create-mirror.html", **valid.kwargs)

    mirror = Mirror()
    mirror.list_subscribe = address
    db.session.add(mirror)
    db.session.flush()
    ml.mirror_id = mirror.id

    mirror_subscribe(ml, mirror)

    UserWebhook.deliver(UserWebhook.Events.list_create,
            ml.to_dict(), UserWebhook.Subscription.user_id == ml.owner_id)

    db.session.commit()
    return redirect(url_for("archives.archive",
            owner_name=current_user.canonical_name,
            list_name=ml.name))

listssrht/templates/create-mirror.html
{% extends "layout.html" %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Create new mirror</h3>
      <p>
        Mirrored lists receive emails from an externally managed mailing list
        and shows them in the {{cfg("sr.ht", "site-name")}} archive.
      </p>
      <form method="POST" action="{{url_for(".create_mirror_POST")}}">
        {{csrf_token()}}
        <div class="form-group">
          <label for="name">Name</label>
          <input
            type="text"
            name="name"
            id="name"
            class="form-control {{valid.cls("name")}}"
            value="{{ name or "" }}" />
          {{valid.summary("name")}}
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea
            name="description"
            id="description"
            class="form-control {{valid.cls("description")}}"
            value="{{ description or "" }}"
            placeholder="Markdown supported"
            rows="5"
            aria-describedby="description-help"
          >{{description or ""}}</textarea>
          {{valid.summary("description")}}
        </div>
        <div class="form-group">
          <label for="address">Subscription address or URL</label>
          <input
            type="text"
            name="address"
            id="address"
            aria-describedby="address-help"
            class="form-control {{valid.cls("address")}}"
            value="{{address or ""}}" />
          {{valid.summary("address")}}
          {% if address and "+subscribe" not in address %}
          <input type="hidden" name="weird-email-okay" value="yes" />
          {% endif %}
        </div>
        <p id="address-help" class="form-text text-muted">
          Take care to use the subscription address - not the posting address.
        </p>
        <button type="submit" class="btn btn-primary">
          Create {{icon("caret-right")}}
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

listssrht/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <div class="col-md-8">
    <p>
      Welcome to <strong>{{domain}}</strong>! This service provides mailing list
      hosting for
      <a href="{{cfg("sr.ht", "site-info")}}">
        {{cfg("sr.ht", "site-name")}}</a>,
      {{cfg("sr.ht", "site-blurb")}}.
      Features of this service include:
    </p>
    <ul>
      <li>Mail submission and patch review via the web</li>
      <li>Threaded, searchable mail archives</li>
      <li>Tools for working with third party mailing lists</li>
    </ul>
    <a
      class="btn btn-primary"
      href="{{get_origin("meta.sr.ht", external=True)}}/register"
    >Register here {{icon('caret-right')}}</a>
    or
    <a href="{{oauth_url}}">
      Log in {{icon('caret-right')}}
    </a>
    to get started.
  </div>
</div>
{% endblock %}

listssrht/templates/list-full.html
{% extends "list.html" %}
{% block nav %}
<nav class="navbar navbar-light navbar-expand-sm">
  {% include 'nav.html' %}
</nav>
{% endblock %}
{% block tabs_container %}
<div class="container-fluid">
{% endblock %}

listssrht/templates/patchset.html
{% extends "list.html" %}
{% block title %}
<title>
  {{ patchset.subject }} &mdash; {{ cfg("sr.ht", "site-name") }} lists
</title>
{% endblock %}
{% macro msg_header(msg, showfrom=True, feedback_block=None) %}
<div class="message-header">
  {% if showfrom %}
  <div class="from">
    {% set from_hdr = msg.parsed()['From'] %}
    {% set from = parseaddr(from_hdr) %}
    {% if msg.sender != None %}
    <a href="/{{ msg.sender.canonical_name }}">{{from[0]}}</a>
    {% else %}
    {{from[0]}}
    {% endif %}
    <a href="{{reply_to(msg)}}">&lt;{{ from[1] }}&gt;</a>
  </div>
  {% endif %}
  <div class="date">
    {% if feedback_block %}
    <a href="#feedback-{{feedback_block.key}}" class="text-muted">
    {% else %}
    <a
      id="{{ msg.message_id }}"
      href="#{{ msg.message_id }}"
      class="text-muted"
    >
    {% endif %}
      {{ msg.created | date }}
    </a>
  </div>
</div>
{% endmacro %}

{% macro display_msg(msg, standalone=True, feedback_block=None) %}
{{ msg_header(msg, feedback_block=feedback_block) }}

{% set feedback = feedback.get(msg.id) %}

<pre class="message-body">
  {%- for line in (feedback_block.body if feedback_block else format_body(msg)).splitlines() -%}
  {{- line + "\n" -}}
  {%- set line_offset = feedback_block.source_region[0] if feedback_block else 0 -%}
  {%- set line_index = loop.index + line_offset - 1 -%}
  {%- if feedback and line_index in feedback.feedback_by_line -%}
</pre>
  {% for sub in feedback.feedback_by_line[line_index] %}
  {% set child = sub.source_msg %}
  <blockquote class="feedback" id="feedback-{{sub.key}}">
    {{ display_msg(child, standalone=False, feedback_block=sub) }}
    {# Generate link to next message fragment #}
    {% set next = nextmsg(feedback, child, line_index) %}
    {% if next %}
    <div style="text-align: right; margin-top: -1rem; margin-bottom: 1rem">
      <a href="#feedback-{{next[1].key}}">
        Next {{icon("caret-right")}}
      </a>
    </div>
    {% endif %}
  </blockquote>
  {% endfor %}
<pre class="message-body">
  {%- endif -%}
{%- endfor -%}
</pre>
{% if any(feedback.standalone_feedback) and standalone %}
{% for feedback in feedback.standalone_feedback %}
{% if feedback.source_msg not in patches %}
<blockquote>
  {% set msg = feedback.source_msg %}
  {{ msg_header(msg) }}
  <pre class="message-body">{{feedback.body}}</pre>
</blockquote>
{% endif %}
{% endfor %}
{% endif %}
{% endmacro %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      {% if user_message %}
      <div class="alert alert-success">
        {{user_message}}
      </div>
      {% endif %}
      {% if patchset.cover_letter %}
      {% set msg = patchset.cover_letter %}
      {% else %}
      {% set msg = patchset.patches[0] %}
      {% endif %}
      <h3>
        {% if patchset.prefix %}
        {{patchset.prefix}}:
        {% endif %}
        {{patchset.subject}}
        <small>v{{patchset.version}}</small>
        <span class="pull-right {{status_to_color[patchset.status]}}">
          {{patchset.status.value.replace("_", " ").upper()}}
        </span>
      </h3>
      {{ msg_header(msg) }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      {% if patchset.cover_letter %}
      <pre class="message-body">{{ format_body(msg) }}</pre>
      {% else %}
      <pre class="message-body">{{ gen_cover_letter(patches) }}</pre>
      {% endif %}

      {% if any(tools) %}
      <div class="event-list tool-status">
        {% for tool in tools %}
        <div class="event">
          {{icon(tool_icon_to_icon[tool.icon],
            cls=tool_icon_to_class[tool.icon])}}
          {{tool_details(tool.details)}}
        </div>
        {% endfor %}
      </div>
      {% endif %}

      {% for m in messages %}
      {% if m.id in feedback %}
      {% set fb = feedback[m.id] %}

      {% for feedback in fb.standalone_feedback %}
      {% set msg = feedback.source_msg %}
        {% if not msg.is_patch %}
          {{ display_msg(msg, standalone=False, feedback_block=feedback) }}
          {# Generate link to next message fragment #}
          {% set next = nextmsg(fb, msg) %}
          {% if next %}
          <div style="text-align: right; margin-top: -1rem; margin-bottom: 1rem">
            <a href="#feedback-{{next[1].key}}">
              Next {{icon("caret-right")}}
            </a>
          </div>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% endif %}
      {% endfor %}
    </div>
    <div class="col-md-4">
      <div class="event-list">
        <div class="event">
          <a class="btn btn-primary btn-block" href="{{ url_for('patches.mbox',
            owner_name=owner.canonical_name, list_name=ml.name,
            patchset_id=patchset.id) }}"
          >Export patchset (mbox) {{icon('caret-right')}}</a>
          <details style="margin-top: 0.5rem">
            <summary>How do I use this?</summary>
            <p>
              Copy &amp; paste the following snippet into your terminal to
              import this patchset into git:
            </p>
            <pre>curl -s {{root}}{{ url_for('patches.mbox',
              owner_name=owner.canonical_name, list_name=ml.name,
              patchset_id=patchset.id) }} | git am -3</pre>
            <a
              href="https://git-send-email.io/"
              target="_blank"
              class="btn btn-link btn-block"
            >Learn more about email &amp; git {{icon('caret-right')}}</a>
          </details>
        </div>
        <div class="event">
          <a class="btn btn-primary btn-block"
            href="{{reply_to(thread.replies[-1] if thread.replies else thread)}}"
          >Reply to thread {{icon('caret-right')}}</a>
          <a class="btn btn-default btn-block" href="{{ url_for('archives.thread',
            owner_name=owner.canonical_name, list_name=ml.name,
            message_id=thread.message_id) }}"
          >View this thread in the archives {{icon('caret-right')}}</a>
          <form
            style="margin-top: 0.5rem"
            action="{{ url_for('archives.forward',
              owner_name=owner.canonical_name, list_name=ml.name,
              message_id=thread.message_id) }}?patch={{patchset.id}}"
            method="POST"
          >
            {{csrf_token()}}
            <button
              class="btn btn-default btn-block"
            >Forward this thread to me {{icon('caret-right')}}</button>
          </form>
        </div>
        {% if ListAccess.moderate in access %}
        <form
          class="event"
          method="POST"
          action="{{url_for('patches.patchset_update',
            owner_name=owner.canonical_name, list_name=ml.name,
            patchset_id=patchset.id)}}"
        >
          {{csrf_token()}}
          <div class="form-group">
            <select
              name="status"
              id="status"
              class="form-control"
            >
              {% for opt in PatchsetStatus %}
              <option
                value="{{opt.value}}"
                {% if patchset.status == opt %}
                selected
                {% endif %}
              >{{opt.value.replace("_", " ").upper()}}</option>
              {% endfor %}
            </select>
          </div>
          <button
            type="submit"
            class="btn btn-success pull-right"
          >Update {{icon('caret-right')}}</button>
          <div class="clearfix"></div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row" style="margin-top: 5rem">
    <div class="col-md-12">
      {% for msg in patches %}
      <h3>
        {{msg.subject}}
        <a href="{{ url_for("archives.raw",
                  owner_name=ml.owner.canonical_name,
                  list_name=ml.name,
                  message_id=msg.message_id
        ) }}" class="btn btn-link pull-right">
          Export this patch {{icon('caret-right')}}
        </a>
      </h3>
      {{ display_msg(msg) }}
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

listssrht/templates/settings-delete.html
{% extends "settings.html" %}
{% block title %}
<title>
  {{ owner.canonical_name }}/{{ ml.name }} settings &mdash; {{ cfg("sr.ht", "site-name") }} lists
</title>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <form method="POST" class="col-md-12">
      <p>
        This will permanently delete your mailing list,
        <strong>{{ owner.canonical_name }}/{{ ml.name }}</strong>.
        This cannot be undone.
      </p>
      <div class="alert alert-info">
        If you <a href="{{url_for("settings.import_export_GET",
          owner_name=owner.canonical_name,
          list_name=ml.name)}}">export your mail spool</a> before deleting this
        mailing list, you may re-import it later or bring it to a different
        service provider.
      </div>
      {{csrf_token()}}
      <button type="submit" class="btn btn-danger">
        Delete {{ml.name}} {{icon("caret-right")}}
      </button>
      <a
        href="{{url_for("archives.archive",
          owner_name=owner.canonical_name, list_name=ml.name)}}"
        class="btn btn-default"
      >Nevermind</a>
    </form>
  </div>
</div>
{% endblock %}